// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpgqfxdkbxBrDVRq42FRN_0fs2wHTVZMM',
    appId: '1:1061688931027:web:9c42d88db3897c14d81a26',
    messagingSenderId: '1061688931027',
    projectId: 'tce-2027-batch',
    authDomain: 'tce-2027-batch.firebaseapp.com',
    storageBucket: 'tce-2027-batch.firebasestorage.app',
    measurementId: 'G-VFFN1YF4FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR_1nlxhOmHE1brS4zlWwAOIYPkig-rYM',
    appId: '1:1061688931027:android:536fa33b5f5c18c3d81a26',
    messagingSenderId: '1061688931027',
    projectId: 'tce-2027-batch',
    storageBucket: 'tce-2027-batch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAofycSGr-IBbkCccil9NTGnYQ9u_luEi0',
    appId: '1:1061688931027:ios:dd057a369b42a66ad81a26',
    messagingSenderId: '1061688931027',
    projectId: 'tce-2027-batch',
    storageBucket: 'tce-2027-batch.firebasestorage.app',
    iosBundleId: 'com.example.tceCab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAofycSGr-IBbkCccil9NTGnYQ9u_luEi0',
    appId: '1:1061688931027:ios:dd057a369b42a66ad81a26',
    messagingSenderId: '1061688931027',
    projectId: 'tce-2027-batch',
    storageBucket: 'tce-2027-batch.firebasestorage.app',
    iosBundleId: 'com.example.tceCab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpgqfxdkbxBrDVRq42FRN_0fs2wHTVZMM',
    appId: '1:1061688931027:web:92f70532fc4d4beed81a26',
    messagingSenderId: '1061688931027',
    projectId: 'tce-2027-batch',
    authDomain: 'tce-2027-batch.firebaseapp.com',
    storageBucket: 'tce-2027-batch.firebasestorage.app',
    measurementId: 'G-KTWFCKGZS9',
  );
}
